### ISSUE TITLE
io.Reader / io.Writer 에 대해서 활용법 및 사용법에 대해 공유가 가능할까요.

### ISSUE THREAD

**Issue by cjaewon** [golangkorea/devfest2020-golang-community-qna#3]
Go 언어를 사용할때 많이 만나게 되는 io.Reader, io.Writer 에 대해 체계적 사용법 및 노하우에 대해서 정보를 듣고싶습니다 ㅜ

**Comment by gigamorph** [comment]
Reader와 Writer는 그냥 각각 하나의 method를 명시한 interface일 뿐인데, 좀더 구체적으로 질문하셔야 (무엇이 이해가 안되는지, 무엇을 하고 싶은지 등등) 답변하실 분들이 이해하기 쉽지 않을까요?

**Comment by gigamorph** [comment]
Reader랑 Writer는 그저 인터페이스일 뿐인데 구체적으로 무엇을 알고 싶으신지 (예를 들어 어떤 어려움이 있었다거나) 궁금하네요 ^^

**Comment by NaniteFactory** [comment]
기본 입출력 인터페이스
- io.Reader
- io.Writer

Java의 InputStream OutputStream Reader Writer 계열의 것들이라고 생각해요.

자주 쓰는 구현체는 이런 것들이 있습니다.
- `bytes.Buffer`: 이게 바이트 버퍼 기본입니다.
- `strings.Builder`: 전 이 녀석을 아주 좋아해요. `bytes.Buffer` 상위 호환입니다.
- `os.File`: 표준 입출력을 비롯한 파일들을 열어볼 때 씁니다.

이 정도만 알아도 편하게 쓸 수 있어요. Java에서처럼 복잡한 클래스 계층도를 안 봐도 되니까 좋아요.

**Comment by cjaewon** [comment]
@gigamorph 제가 자세히 썼어야 하는데 죄송합니다ㅜ

일단 저는 io.Reader / io.Writer 활용되는 곳 및 인터페이스를 이용해서 Buffer / os.File 같은 타입들을 어떻게 받을 수 있는 지가 궁금했습니다. 현재 해당 타입 메소드에 read / write 라는 함수가 포함되어 있으면 io.Writer io.Reader 타입으로 받을 수 있다는 사실을 이제야 알겠됬습니다ㅜ
