### ISSUE TITLE
Go module 사용할 때 module path에 관한 규칙

### ISSUE THREAD

**Issue by gigamorph** [golangkorea/devfest2020-golang-community-qna#4]
Module 정의 할 때 path를 명시해야 하잖아요. 예를 들어
```
go mod init github.com/dodo/flyhigh
```
여기서 `github.com`은 깃헙 호스트, `dodo`는 깃헙 유저 아이디, `flyhigh`가 프로젝트 이름인데 이 형식에서 조금이라도 벗어나면 안되는 건지 알고 싶습니다. (검색을 해봐도 GitHub 예만 나와서요.) 그러니까

* GitHub 말고는 Go 모듈을 배포할 수 없는 것인가. 예를 들어 `my.repository.io/dodo/flyhigh`
* Path의 레벨이 더 깊어질 수는 없는 것인가. 예를 들어 `github.com/dodo/my/flyhigh` -- 제가 시도해 본 바로는 `my/` 레벨에 go.mod가 없으면 에러가 나는 것 같더라구요

감사합니다.

**Comment by billopark** [comment]
https://gitea.com/xorm/xorm/src/branch/master/go.mod
꼭 github이 아니어도 되고, path도 크게 무관할 것 같아요
