### ISSUE TITLE
백엔드 서버를 만들때 golang이 python, node, java 와 같은 다른 언어들 보다 좋은점이 뭐가 있을까요

### ISSUE THREAD

**Issue by Ghun2** [golangkorea/devfest2020-golang-community-qna#5]
백엔드 서버를 만들때 golang이 python, node, java 와 같은 다른 언어들 보다 좋은점이 뭐가 있을까요.
차별점과 장단점을 알고 싶습니다.

**Comment by gigamorph** [comment]
직접 엄밀하게 실험해보진 않았지만, Go가 상대적으로 빠르다고들 하고요 (체감적으로도 Python이나 Ruby보다는 확실히 빠른 것 같고), Java보다 빠른지는 확실히 모르겠는데 편견인지 모르겠지만 Java는 간단한 프로그램 만들어도 사이즈가 커지는 것 같아서.

적어도 마이크로서비스라고나 할까, 소규모 서버를 만들 때에는 C 비슷하게 빠르면서 C보다 간편하게 코딩할 수 있고, 그런게 좋은 것 같아요. Node는, 잘 모르겠네요, 언어 생긴 모양은 딱히 어느 쪽을 선호하기 어렵고, 특히 Go에 NPM같은 package manager가 있으면 하는 생각도 들고 하는데, Go 마스코트가 귀엽죠. ㅎㅎ

**Comment by yundream** [comment]
무자비한 실용성과 단순성이 첫 번째 장점이라고 생각합니다. 이를 위해서 기능과 유연함을 일정부분 포기했습니다. 이러한 단순함이 잘 어울리는 영역에서 힘을 발휘하고 있습니다. 클라우드 환경이 첫번째가 되겠네요. 클라우드 환경 자체가 기능과 유연성을 외부에 위임하는 형태이기 때문에, 이 경우 언어는 굳이 복잡하게 많은 기능을 가질 필요가 없습니다.

배포의 용이함이 장점입니다. 구글은 go 언어를 자신들이 운영하는 클라우드 환경에서 작동하는 소프트웨어의 개발을 위해서 만들었는데, 이런 복잡한(위임된) 시스템에서는 빠른 컴파일과 배포가 매우 중요한 요소가 됩니다.

성능은 python, ruby 등의 스트립트 언어보다 훨씬 빠르고, java와 비슷한 수준의 성능을 보여줍니다.

전반적으로 golang을 이용하면 클라우드, MSA, 컨테이너 기반 시스템에 낮은 학습곡선으로 적절한 성능을 보여주며, 빠르게 배포하는 애플리케이션을 만들 수 있습니다.

**Comment by billopark** [comment]
일반적으로 Go가 다른 언어들에 비해서 특별한 점은 언어가 간결하여 러닝커브가 낮고, binary로 빠르게 빌드되며 실행속도도 빠르다는 것과, 언어에 docker와 같은 큰 프로젝트에서 검증되었다는 것, Go-1 Promise로 compatibility를 덜 신경써도 된다는 점, type-safe하며 상대적으로 쉬운 동시성 처리, 명시적인 에러 핸들링, Magical하지 않다는 특징등이 있을 것 같습니다. 그리고 백엔드 서버 서비스를 위한 기본적인 기능들이 net/http에 잘 구현되어 있다는 것도 좋은 부분이죠.

node와 python같은 스크립트 언어와 비교해서는 따로 런타임이 필요없고 type-safe한 점이 부각될 것 같고, python에 비해서는 동시성 처리가 훨씬 낫고, node에 비교해서는 [더 안정적인 언어 스펙](https://www.reddit.com/r/ProgrammerHumor/comments/6tifn2/the_holy_trinity_and_javascript/), callback없는 코드등이 낫지 않을까 싶어요.
그리고 java와 비교해서는 상대적으로 언어가 젊다는 점, 같은 내용의 코드를 짜도 짧은 코드안에 핵심을 전달할 수 있는 가독성, 스레드 적인 측면에서의 우위, JVM같은 런타임이 필요없는 것이 있을 것 같습니다.

**Comment by NaniteFactory** [comment]
Go로 구현한 것이 언급하신 나머지 언어로 구현한 것보다 특별히 크게 더 빠르거나 하지 않습니다. 최적화 정도에 따라 다르지만 실사용시 Java로 구현한 것보다도 때때로 더 느린 수준이에요. 참고자료나 패키지도 다른 언어에 비교해서 턱 없이 적고요.

그럼에도 불구하고 Go의 장점을 꼽아 보자면

### 1. 코드가 깨끗하게 나오고 문서화가 쉬움
- GoDoc의 존재: GoDoc 하나만으로도 문서화가 너무 편합니다.
- 불필요한 키워드의 제거: 잡다한 syntatic sugar나 public private while 같은 쓸모 없는 키워드를 모두 없애 놓아서 구문이 간결합니다.
- 클래스와 상속의 부재: 클래스와 상속은 GoF와 James Gosling이 악으로 규정했던 개념인데, 이것을 없애면서 코드가 간결해지고 나쁜 디자인 패턴을 사용하는 것이 언어 차원에서 금지되었습니다. (Go 프로그래머는 상속 대신 전략 패턴을 씁니다.)

### 2. 오픈소스
- Git/Github과 완벽하게 연동되고 다른 사람의 작업물을 끌어오거나 공유하기가 너무 쉽습니다. Git 쓸 줄 알고 `go get` `go mod`만 쓸 줄 알면 되니까요.

### 3. 네이티브 바이너리로 컴파일
- Python, Node, Java 같은 종전의 크로스 플랫폼 언어들은 모두 VM에 의존적이었지만, Go는 C++처럼 VM 기반이지 않으면서 C 형식에 완벽하게 호환되는 네이티브 바이너리를 빠르게 빌드해 냅니다.
- VM 기반 프로그래밍 언어로 이룰 수 없는 저수준 프로그래밍이 가능합니다.

### 4. 병행성
- 고루틴, 채널, 콘텍스트: 다른 언어에서 하고 있는 것처럼 쓰레드를 직접 끌어와서 쓰지 않기 때문에 병행 처리시 큰 이점이 있습니다.

### 5. 엄격한 타입 시스템
- 타입에 대해 엄격하면 암시적인 요소가 줄어들어서 그렇지 않은 것에 비해 소스코드가 더 읽기 쉽고 디버깅하기 쉽습니다.

장점은 이 정도고 장점이면서 동시에 단점인 게 한 가지 있는데, 

### 6. 쓰레기 수집(GC)
- VM 없이 쓰레기 수집기가 동작할 수 있는 것은 장점이지만, Go 프로그램의 CPU 사용량이 주기적으로 치솟는 이유기도 합니다. 쓰레기 수집기가 Go 프로그램에서 치명적인 성능상 병목이 되는 것 때문에 Go로 개발하던 사람들이 Rust 같은 언어로 넘어가는 경향이 있습니다.
