### ISSUE TITLE
고 개발시 어떤 IDE 추천하시나요?

### ISSUE THREAD

**Issue by urangurang** [golangkorea/devfest2020-golang-community-qna#8]
VSCODE?　GOLAND?　이외에도 다양한 IDE가 있을것으로 생각되는데 어떤 IDE를 주로 사용하시는지 궁금합니다.
더불어 개발시 유용한 플러그인이 있다면 추천 부탁드립니다.

**Comment by NaniteFactory** [comment]
Go 언어로 개발할 때는 기본 툴체인 외에 다른 IDE나 플러그인은 일절 사용하지 않습니다.
VSCode는 IDE가 아니라 텍스트 에디터 정도 되지요.
코드 편집기는 VSCode가 최고입니다.

**Comment by KennethanCeyer** [comment]
저는 [GoLand](https://www.jetbrains.com/go/promo/?gclid=CjwKCAjwrKr8BRB_EiwA7eFaptbKHIdHntIiXozUuD47_lXkdVMDDCbVXOAARaHB4tyAl4iQBnjMShoCW5QQAvD_BwE) 추천합니다.
Jetbrains의 Refactoring 기능은 아시는분은 아시겠지만 세계 최고죠!
~러시아에서는 코드가 사람을 작성합니다.~

**Comment by billopark** [comment]
저도 GoLand에 +1 드립니다. 좋은 툴이에요!
LiteIDE와 같은 것들은 수년전 사용해봤는데 사용성이 영 떨어지더라고요.
GoLand 쓰기 전에는 VSCode를 사용했습니다. (VSCode전에는 Atom을 썼었네요..)

**Comment by yundream** [comment]
VSCode를 사용하고 있는데, GoLand를 한번 살펴봐야 겠네요.
