### ISSUE TITLE
대한민국 기업 중 golang을 사용하는 기업이 어디있고, 어느 분야에서 많이 사용되나요?

### ISSUE THREAD

**Issue by Enoch-Kim** [golangkorea/devfest2020-golang-community-qna#9]
1. 이름있는 기업을 알고 싶습니다. (취업하려고 알아보니 찾기 어렵더라구요 ㅠㅠ)
2. 서버에서도 클라우드, 서비스 등등 분야를 알고 싶어요.

**Comment by KennethanCeyer** [comment]
네이버는 여러 분야에서 Golang을 잘 사용하고 있습니다.
- [D2 NAVER Golang](https://d2.naver.com/search?keyword=Go%EC%96%B8%EC%96%B4)
- [TechTalk Golang](https://tv.naver.com/v/5614347)

**Comment by yundream** [comment]
이전에 몸 담았던 네이버랩스에서도 Go 언어를 사용했습니다. 얼마전에 랩스에서 Go 개발자 뽑더군요. 현대 자동차 플랫폼/서비스 개발 팀도 Go 개발자를 뽑고 있고요.
